# CONFIGURACIÓN LOCAL (POOLER DE SUPABASE)
# Nota: Puerto 6543 y sslmode=require
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.bwqaxblmleayruibinll
spring.datasource.password=LU68m5NA00KbIYVM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true